# -*- coding: utf-8 -*-
"""patient1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_k-Qayb6qd2BKXmFfjH-6Er7nVWTZ58Y
"""

from flask import*
patient1=Blueprint('patient1',__name__)

@patient1.route('/',methods=["GET","POST"])
def main():

    if 'submit' in request.form:
        patientid=request.form['patientid']
        profit=request.form['profit']
        price=request.form['price']
        cost=request.form['cost']
        discount=request.form['discount']
        zipcode=request.form['zipcode']
      

        import numpy 
        import pandas as pd

        df = pd.read_csv("Patient-Info.csv")
        x=df.iloc[:,0:18].values
        y=df.iloc[:,8].values
        df

        y

        x

        Z=df.loc[:, ~df.columns.isin(['Admit Date','Discharge Date','Payor Segment','Service','Category','Sub Category','Physician','Region','Hospital', 'Priority','Function','State'])]

        Z

        X=Z.loc[:, Z.columns!='Revenue'].values
        X

        Y=Z.loc[:,"Revenue"].values
        Y

        #split the data in to training set and test set
        #import train_test_split
        from sklearn.model_selection import train_test_split
        X_train,X_test,Y_train,Y_test = train_test_split(X , Y , test_size=1/3,random_state=0)

        X

        X_train.shape

        Y_train.shape

        X_test

        Y_test

            #import linear regression
            #creating an obj called obj
        from sklearn.linear_model import LinearRegression
        obj = LinearRegression()
        obj.fit(X_train,Y_train)

        h = []
        h.append(patientid)
        h.append(profit)
        h.append(price)
        h.append(cost)
        h.append(discount)
        h.append(zipcode)

        arr=numpy.array(h,dtype=float)
        result=obj.predict([arr])
        return render_template('Index.html',result="{}".format(result[0]))

    
    return render_template('Index.html')


